config/routes.rb
Rails.application.routes.draw do
  # routes由上往下判定，可以把常去的頁面放最上面
  resources :categories

  resources :items do
    resources :comments, only:[:create]
    # /new 不需要是因為，已經在show頁面有欄位，不需要一個獨立頁面
    # /create
    member do
      post :add_to_cart
    end
  end

  #cart
  # post "/abc/:id", to: "cart#add", as: :cart

  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  # resources :comments
  #/:id
  #/:id


  # get "/", to: "welcome#index"
  root "items#index"
  get "/login", to: "users#login"
  post "/login", to: "users#signin"
  delete "/logout", to: "users#logout"

  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"

  #APIs 
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do 
          post :favorite
        end
      end
    end
  end

  #order
  resources :orders, only: [:index, :show, :create] do
    member do
      delete :cancel
    end
  end


end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice]%>
    <button><i class="fas fa-times"></i></button>
    
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<p>版權宣告 2020 &copy; BB</p>

app/views/shared/_navbar.html.erb
<!-- 
<%#= flash[:notice]%>
-->


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">ASC4便當團</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to '餐點列表', items_path, class: 'nav-link' %>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <% current_user %>
        </li>
        <li class="nav-item">
         <%= link_to "我要開團", '#', class: 'nav-link' %>
        </li>
      <% end %>
    </ul>

    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item">
          <a class="nav-link" disabled>
          <%= current_user.email %>
          </a>
          
        </li>
        <li class="nav-item ">
          <%# <%= link_to "Cart <i class='fas fa-shopping-cart'></i>".html_safe, 'add_to_cart_item_path(item)', class: 'nav-link' %>
          <%= link_to cart_path, class: 'nav-link' do %>
            Cart <i class='fas fa-shopping-cart'></i> <%= current_cart.items.count%>
          <% end%>
        </li>
        <li class="nav-item ">
          <%= link_to "logout", logout_path, method: 'delete', class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <a href="/sign_up" class="nav-link">sign up</a>
        </li>
        <li class="nav-item">
          <a href="/login" class="nav-link">log in</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>