config/routes.rb
Rails.application.routes.draw do
  # routes由上往下判定，可以把常去的頁面放最上面
  resources :categories

  resources :items do
    resources :comments, only:[:create]
    # /new 不需要是因為，已經在show頁面有欄位，不需要一個獨立頁面
    # /create
    member do
      post :add_to_cart
    end
  end

  #cart
  # post "/abc/:id", to: "cart#add", as: :cart

  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  # resources :comments
  #/:id
  #/:id


  # get "/", to: "welcome#index"
  root "items#index"
  get "/login", to: "users#login"
  post "/login", to: "users#signin"
  delete "/logout", to: "users#logout"

  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"

  #APIs 
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do 
          post :favorite
        end
      end
    end
  end

  #order
  resources :orders, only: [:index, :show, :create] do
    member do
      delete :cancel
    end
  end


end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end
  
  def add_item(item_id)
    found_item = items.find { |item| item.item_id == item_id }

    if found_item
      found_item.increment!
    else
      items << CartItem.new(item_id)
    end

  end

  def empty?
    items.empty?
  end

  # def items
  #   @items
  # end

  def total
    result = items.reduce(0) { |sum, item| sum + item.total }
    if Time.now.month == 4 and Time.now.day == 1
      # 4/1全館打1折
      result = result * 0.1
    end
    return result

    # @items.sum { |item| item.total}

    # tmp = 0
    # @items.each do |item|
    #   tmp += item.total
    # end
  end

  def to_hash
    # items = [
    #   { "item_id" => 1, "quantity" => 3},
    #   { "item_id" => 2, "quantity" => 2}
    # ]

    # items = []
    # @items.each do |item|
    #   items << { "item_id" => item.item_id,
    #              "quantity" => item.quantity }

    # end

    items = @items.map{ |item| 
    { "item_id" => item.item_id,
      "quantity" => item.quantity }
    }

    result = {
      "items" => items
    }
  end

  def self.from_hash(hash = nil)
    if hash && hash["items"]
      # items = []
      # hash["items"].each do |item|
      #   items << CartItem.new(item["item_id"], item["quantity"])
      # end

      items = hash["items"].map { |item| 
      CartItem.new(item["item_id"], item["quantity"])
      }
      # Cart.new(items)
      new items
    else
      # Cart.new
      new #類別內直接呼叫類別方法即可，不用Cart也可以用
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # def show
  # end

  def destroy
    session[:carty] = nil
    redirect_to root_path, notice: '購物車已清空'
  end

  def checkout
    @order = Order.new

    @token = gateway.client_token.generate
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% if not current_cart.empty? %>
<table class="table table-dark">
  <thead>
    <tr>
      <th>餐點</th>
      <th>數量</th>
      <th>小計</th>
    </tr>
  </thead>
  <tbody>
    <% current_cart.items.each do |cart_item| %>
    <tr>
      <th><%= cart_item.item.name %>(<%= cart_item.item.price %>元)</th>
      <th><%= cart_item.quantity %></th>
      <th><%= cart_item.total %></th>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2">總計</td>
      <td><%= current_cart.total  %></td>
    </tr>
  </tfoot>
</table>

<% else %>

<% end %>

app/views/carts/checkout.html.erb
<%= content_for :head_js  do %>
<script defer src="https://js.braintreegateway.com/web/dropin/1.22.1/js/dropin.min.js"></script>
<% end %>




<%= render 'cart'%>

<%= form_for(@order) do |form| %>
<div>
  <%= form.label :receiver %>
  <%= form.text_field :receiver %>
</div>

<div>
  <%= form.label :phone%>
  <%= form.text_field :phone%>
</div>

<div>
  <%= form.label :address%>
  <%= form.text_field :address%>
</div>

<%= form.hidden_field :nonce %>

<div id="dropin-container"></div>

<%= form.submit id: 'submit-order' %>

<% end %>

<script>

document.addEventListener("turbolinks:load", function() {
  let button = document.querySelector('#submit-order')
  let nonce_field = document.querySelector('#order_nonce')
  let form = document.querySelector('#new_order')
  braintree.dropin.create({
      authorization: '<%= @token %>',
      container: '#dropin-container'
    }, function (createErr, instance) {
      button.addEventListener('click', function (e) {
        e.preventDefault();
        instance.requestPaymentMethod(function (err, payload) {
          nonce_field.value = payload.nonce;
          form.submit();
          // console.log(payload.nonce);
          // Submit payload.nonce to your server
        });
      });
    });
});

</script>

app/views/carts/show.html.erb
<h1>Cart Detail <%= link_to '清空購物車', cart_path, method: 'delete', class: 'btn btn-sm btn-warning' unless current_cart.empty? %></h1>

<%= render 'cart'%>

<%= link_to '繼續選購', root_path, class: 'btn btn-info' %>
<%= link_to '結帳', checkout_cart_path , class: 'btn btn-success' unless current_cart.empty? %>