config/routes.rb
Rails.application.routes.draw do
  # routes由上往下判定，可以把常去的頁面放最上面
  resources :categories

  resources :items do
    resources :comments, only:[:create]
    # /new 不需要是因為，已經在show頁面有欄位，不需要一個獨立頁面
    # /create
    member do
      post :add_to_cart
    end
  end

  #cart
  # post "/abc/:id", to: "cart#add", as: :cart

  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  # resources :comments
  #/:id
  #/:id


  # get "/", to: "welcome#index"
  root "items#index"
  get "/login", to: "users#login"
  post "/login", to: "users#signin"
  delete "/logout", to: "users#logout"

  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"

  #APIs 
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do 
          post :favorite
        end
      end
    end
  end

  #order
  resources :orders, only: [:index, :show, :create] do
    member do
      delete :cancel
    end
  end


end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0} 

  belongs_to :category
  has_one_attached :cover
  has_many :comments
  has_many :favorite_items
  has_many :users, through: :favorite_items
  # scope :available, ->{ where(deleted_at: nil)} # 會定義出一個.available類別方法

  default_scope { where(deleted_at: nil) }
  
  def destroy
    update(deleted_at: Time.now)
  end

  def favorite_by(u)
    u.items.include?(self)
  end

end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < ApplicationController
  # skip_before_action :verify_authenticity_token
  # skip_before_action :check_login
  def favorite
    item = Item.find(params[:id]) #先把資料翻出來
    if item.favorite_by(current_user)
      #移除最愛
      current_user.items.delete(item)
      render json: {status: 'removed'}
    else
      #加最愛
      current_user.items << item
      render json: {status: 'favorited'}
    end

    # render json: {name: 'aaa', age: 18}
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy, :add_to_cart]
  def index
    # @items = Item.all
    # @items = Item.where(deleted_at: nil)
    # @items = Item.available
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path, notice: 'Items had been added!'
    else
      render :new
    end   
  end

  def show
    @category = @item.category.name
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def edit
  end

  def update
    # debugger
    if @item.update(item_params)
      redirect_to item_path, notice: '成功更新餐點'
    else
      render :edit
      # redirect_to item_path
    end
  end

  def destroy
    @item.destroy
    # @item.update(deleted_at: Time.now)
    redirect_to items_path, notice: '成功刪除餐點'
  end

  def add_to_cart
    current_cart.add_item(@item.id)
    session[:carty] = current_cart.to_hash

    redirect_to '/', notice: 'OK 加到購物車'
  end

  private
  def item_params
    params.require(:item).permit(:name,
                                 :price,
                                 :description,
                                 :category_id,
                                 :spec,
                                 :cover)
  end
  def find_item
    @item = Item.find(params[:id])
    # @item = Item.find_by!(id: params[:id], deleted_at: nil) #Item.available
  end
end

app/helpers/api/v1/items_helper.rb
module Api::V1::ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %> 
  <ul>
    <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <div>
    <%= f.label :cover%>
    <%= f.file_field :cover%>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true %>
  </div>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div>
    <%= f.label :spec %>
    <%= f.text_field :spec %>
  </div>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>編輯資料</h1>
<%= render 'form', item: @item %>

app/views/items/index.html.erb
<h1>餐點列表</h1>
<%= link_to "新增", new_item_path %>
<%= link_to 'Category', categories_path %>

  <div class="row">
    <% @items.each do |item| %>
      <div class="col-12 col-md-4 item">
        <div class="card mt-3">
          <!-- <img src="https://fakeimg.pl/300x200/" alt=""> -->
          <div class="cover-image">
            <!-- <img src="https://picsum.photos/100/200?random=11" class="card-img w-100 h-auto"  alt=""> -->
            <%= image_tag item.cover.variant(resize_to_limit: [500, 500]) if item.cover.attached? %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to item.name, item_path(item.id) %></h5>
            <p class="card-text">分類：<%= item.category.name %></p>
            <%= link_to "編輯", edit_item_path(item.id), class: 'btn btn-info' %>
            <%= link_to "刪除", item_path(item.id), class: 'btn btn-danger', method: 'delete', data: {confirm: "是否確認刪除?"} %>
            <%= link_to "+Cart", add_to_cart_item_path(item), class: 'btn btn-warning',method: 'post' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<%= javascript_pack_tag 'item', 'data-turbolinks-track': 'reload' %>
  <!-- <div class="box">
    <img src="https://picsum.photos/300/500?random=11" alt="">
  </div> -->

app/views/items/new.html.erb
<h1>新增餐點</h1>

<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %> 
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div>
    <%= f.label :spec %>
    <%= f.text_field :spec %>
  </div>
  <%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1 data-controller="item">
<%= @item.name %>
<%# <i class = "fas fa-heart"></i> %>
  <a href="#" class="btn btn-danger" data-action="item#heart">
    <% if @item.favorite_by(current_user) %>
    <i class="fas fa-heart" data-target="item.icon"></i> <!-- 加data-->
    <% else %>
    <i class="far fa-heart" data-target="item.icon"></i> <!-- 加data-->
    <% end %>
  </a>
  <%= link_to "+Cart", add_to_cart_item_path(@item), class: 'btn btn-warning',method: 'post' %>
</h1>

<h1>價錢：<%= @item.price %></h1>
<h1>分類：<%= @category %></h1>

<div data-controller="comment">
  <h3>留言</h3>
  <%= form_for(@comment, url: item_comments_path(@item), remote: true) do |form| %>

  <input type="hidden" id="item_id" value="<%= @item.id %>">

    <div class="form-group">  
      <%= form.text_area :content ,
                    class: 'form-control', 
                    data: {target: 'comment.content', 
                           action: 'keyup->comment#check'}%>
    </div>
  <%= form.submit class: 'btn btn-info', disabled: true, data: {target: 'comment.submit'} %>
  <% end %>
</div>

<hr>

<div id="comments"></div>

<% @comments.each do |comment| %>
<%= render 'comments/comment', comment: comment %>
<% end %>